<?php
/**
 * CountryCode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * airEml - API (full)
 *
 * airEml - API (full)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CountryCode Class Doc Comment
 *
 * @category Class
 * @description The country code is a two-letter code like UkrAine - ua or United States - us defined in ISO-3166 Alpha-2. Details https://www.iso.org/glossary-for-iso-3166.html Don&#39;t set it to send sms by your number to the all countries.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CountryCode
{
    /**
     * Possible values of this enum
     */
    public const AF = 'af';

    public const AX = 'ax';

    public const AL = 'al';

    public const DZ = 'dz';

    public const _AS = 'as';

    public const AD = 'ad';

    public const AO = 'ao';

    public const AI = 'ai';

    public const AQ = 'aq';

    public const AG = 'ag';

    public const AR = 'ar';

    public const AM = 'am';

    public const AW = 'aw';

    public const AU = 'au';

    public const AT = 'at';

    public const AZ = 'az';

    public const BS = 'bs';

    public const BH = 'bh';

    public const BD = 'bd';

    public const BB = 'bb';

    public const BY = 'by';

    public const BE = 'be';

    public const BZ = 'bz';

    public const BJ = 'bj';

    public const BM = 'bm';

    public const BT = 'bt';

    public const BO = 'bo';

    public const BA = 'ba';

    public const BW = 'bw';

    public const BV = 'bv';

    public const BR = 'br';

    public const IO = 'io';

    public const VG = 'vg';

    public const BN = 'bn';

    public const BG = 'bg';

    public const BF = 'bf';

    public const BI = 'bi';

    public const KH = 'kh';

    public const CM = 'cm';

    public const CA = 'ca';

    public const CV = 'cv';

    public const BQ = 'bq';

    public const KY = 'ky';

    public const CF = 'cf';

    public const TD = 'td';

    public const CL = 'cl';

    public const CN = 'cn';

    public const CX = 'cx';

    public const CC = 'cc';

    public const CO = 'co';

    public const KM = 'km';

    public const CG = 'cg';

    public const CD = 'cd';

    public const CK = 'ck';

    public const CR = 'cr';

    public const CI = 'ci';

    public const HR = 'hr';

    public const CU = 'cu';

    public const CW = 'cw';

    public const CY = 'cy';

    public const CZ = 'cz';

    public const DK = 'dk';

    public const DJ = 'dj';

    public const DM = 'dm';

    public const _DO = 'do';

    public const EC = 'ec';

    public const EG = 'eg';

    public const SV = 'sv';

    public const GQ = 'gq';

    public const ER = 'er';

    public const EE = 'ee';

    public const SZ = 'sz';

    public const ET = 'et';

    public const FK = 'fk';

    public const FO = 'fo';

    public const FJ = 'fj';

    public const FI = 'fi';

    public const FR = 'fr';

    public const GF = 'gf';

    public const PF = 'pf';

    public const TF = 'tf';

    public const GA = 'ga';

    public const GM = 'gm';

    public const GE = 'ge';

    public const DE = 'de';

    public const GH = 'gh';

    public const GI = 'gi';

    public const GR = 'gr';

    public const GL = 'gl';

    public const GD = 'gd';

    public const GP = 'gp';

    public const GU = 'gu';

    public const GT = 'gt';

    public const GG = 'gg';

    public const GN = 'gn';

    public const GW = 'gw';

    public const GY = 'gy';

    public const HT = 'ht';

    public const HM = 'hm';

    public const HN = 'hn';

    public const HK = 'hk';

    public const HU = 'hu';

    public const IS = 'is';

    public const IN = 'in';

    public const ID = 'id';

    public const IR = 'ir';

    public const IQ = 'iq';

    public const IE = 'ie';

    public const IM = 'im';

    public const IL = 'il';

    public const IT = 'it';

    public const JM = 'jm';

    public const JP = 'jp';

    public const JE = 'je';

    public const JO = 'jo';

    public const KZ = 'kz';

    public const KE = 'ke';

    public const KI = 'ki';

    public const KW = 'kw';

    public const KG = 'kg';

    public const LA = 'la';

    public const LV = 'lv';

    public const LB = 'lb';

    public const LS = 'ls';

    public const LR = 'lr';

    public const LY = 'ly';

    public const LI = 'li';

    public const LT = 'lt';

    public const LU = 'lu';

    public const MO = 'mo';

    public const MG = 'mg';

    public const MW = 'mw';

    public const MY = 'my';

    public const MV = 'mv';

    public const ML = 'ml';

    public const MT = 'mt';

    public const MH = 'mh';

    public const MQ = 'mq';

    public const MR = 'mr';

    public const MU = 'mu';

    public const YT = 'yt';

    public const MX = 'mx';

    public const FM = 'fm';

    public const MD = 'md';

    public const MC = 'mc';

    public const MN = 'mn';

    public const ME = 'me';

    public const MS = 'ms';

    public const MA = 'ma';

    public const MZ = 'mz';

    public const MM = 'mm';

    public const NA = 'na';

    public const NR = 'nr';

    public const NP = 'np';

    public const NL = 'nl';

    public const NC = 'nc';

    public const NZ = 'nz';

    public const NI = 'ni';

    public const NE = 'ne';

    public const NG = 'ng';

    public const NU = 'nu';

    public const NF = 'nf';

    public const KP = 'kp';

    public const MK = 'mk';

    public const MP = 'mp';

    public const NO = 'no';

    public const OM = 'om';

    public const PK = 'pk';

    public const PW = 'pw';

    public const PS = 'ps';

    public const PA = 'pa';

    public const PG = 'pg';

    public const PY = 'py';

    public const PE = 'pe';

    public const PH = 'ph';

    public const PN = 'pn';

    public const PL = 'pl';

    public const PT = 'pt';

    public const PR = 'pr';

    public const QA = 'qa';

    public const RE = 're';

    public const RO = 'ro';

    public const RU = 'ru';

    public const RW = 'rw';

    public const WS = 'ws';

    public const SM = 'sm';

    public const ST = 'st';

    public const SA = 'sa';

    public const SN = 'sn';

    public const RS = 'rs';

    public const SC = 'sc';

    public const SL = 'sl';

    public const SG = 'sg';

    public const SX = 'sx';

    public const SK = 'sk';

    public const SI = 'si';

    public const SB = 'sb';

    public const SO = 'so';

    public const ZA = 'za';

    public const GS = 'gs';

    public const KR = 'kr';

    public const SS = 'ss';

    public const ES = 'es';

    public const LK = 'lk';

    public const BL = 'bl';

    public const SH = 'sh';

    public const KN = 'kn';

    public const LC = 'lc';

    public const MF = 'mf';

    public const PM = 'pm';

    public const VC = 'vc';

    public const SD = 'sd';

    public const SR = 'sr';

    public const SJ = 'sj';

    public const SE = 'se';

    public const CH = 'ch';

    public const SY = 'sy';

    public const TW = 'tw';

    public const TJ = 'tj';

    public const TZ = 'tz';

    public const TH = 'th';

    public const TL = 'tl';

    public const TG = 'tg';

    public const TK = 'tk';

    public const TO = 'to';

    public const TT = 'tt';

    public const TN = 'tn';

    public const TR = 'tr';

    public const TM = 'tm';

    public const TC = 'tc';

    public const TV = 'tv';

    public const UM = 'um';

    public const VI = 'vi';

    public const UG = 'ug';

    public const UA = 'ua';

    public const AE = 'ae';

    public const GB = 'gb';

    public const US = 'us';

    public const UY = 'uy';

    public const UZ = 'uz';

    public const VU = 'vu';

    public const VA = 'va';

    public const VE = 've';

    public const VN = 'vn';

    public const WF = 'wf';

    public const EH = 'eh';

    public const YE = 'ye';

    public const ZM = 'zm';

    public const ZW = 'zw';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AF,
            self::AX,
            self::AL,
            self::DZ,
            self::_AS,
            self::AD,
            self::AO,
            self::AI,
            self::AQ,
            self::AG,
            self::AR,
            self::AM,
            self::AW,
            self::AU,
            self::AT,
            self::AZ,
            self::BS,
            self::BH,
            self::BD,
            self::BB,
            self::BY,
            self::BE,
            self::BZ,
            self::BJ,
            self::BM,
            self::BT,
            self::BO,
            self::BA,
            self::BW,
            self::BV,
            self::BR,
            self::IO,
            self::VG,
            self::BN,
            self::BG,
            self::BF,
            self::BI,
            self::KH,
            self::CM,
            self::CA,
            self::CV,
            self::BQ,
            self::KY,
            self::CF,
            self::TD,
            self::CL,
            self::CN,
            self::CX,
            self::CC,
            self::CO,
            self::KM,
            self::CG,
            self::CD,
            self::CK,
            self::CR,
            self::CI,
            self::HR,
            self::CU,
            self::CW,
            self::CY,
            self::CZ,
            self::DK,
            self::DJ,
            self::DM,
            self::_DO,
            self::EC,
            self::EG,
            self::SV,
            self::GQ,
            self::ER,
            self::EE,
            self::SZ,
            self::ET,
            self::FK,
            self::FO,
            self::FJ,
            self::FI,
            self::FR,
            self::GF,
            self::PF,
            self::TF,
            self::GA,
            self::GM,
            self::GE,
            self::DE,
            self::GH,
            self::GI,
            self::GR,
            self::GL,
            self::GD,
            self::GP,
            self::GU,
            self::GT,
            self::GG,
            self::GN,
            self::GW,
            self::GY,
            self::HT,
            self::HM,
            self::HN,
            self::HK,
            self::HU,
            self::IS,
            self::IN,
            self::ID,
            self::IR,
            self::IQ,
            self::IE,
            self::IM,
            self::IL,
            self::IT,
            self::JM,
            self::JP,
            self::JE,
            self::JO,
            self::KZ,
            self::KE,
            self::KI,
            self::KW,
            self::KG,
            self::LA,
            self::LV,
            self::LB,
            self::LS,
            self::LR,
            self::LY,
            self::LI,
            self::LT,
            self::LU,
            self::MO,
            self::MG,
            self::MW,
            self::MY,
            self::MV,
            self::ML,
            self::MT,
            self::MH,
            self::MQ,
            self::MR,
            self::MU,
            self::YT,
            self::MX,
            self::FM,
            self::MD,
            self::MC,
            self::MN,
            self::ME,
            self::MS,
            self::MA,
            self::MZ,
            self::MM,
            self::NA,
            self::NR,
            self::NP,
            self::NL,
            self::NC,
            self::NZ,
            self::NI,
            self::NE,
            self::NG,
            self::NU,
            self::NF,
            self::KP,
            self::MK,
            self::MP,
            self::NO,
            self::OM,
            self::PK,
            self::PW,
            self::PS,
            self::PA,
            self::PG,
            self::PY,
            self::PE,
            self::PH,
            self::PN,
            self::PL,
            self::PT,
            self::PR,
            self::QA,
            self::RE,
            self::RO,
            self::RU,
            self::RW,
            self::WS,
            self::SM,
            self::ST,
            self::SA,
            self::SN,
            self::RS,
            self::SC,
            self::SL,
            self::SG,
            self::SX,
            self::SK,
            self::SI,
            self::SB,
            self::SO,
            self::ZA,
            self::GS,
            self::KR,
            self::SS,
            self::ES,
            self::LK,
            self::BL,
            self::SH,
            self::KN,
            self::LC,
            self::MF,
            self::PM,
            self::VC,
            self::SD,
            self::SR,
            self::SJ,
            self::SE,
            self::CH,
            self::SY,
            self::TW,
            self::TJ,
            self::TZ,
            self::TH,
            self::TL,
            self::TG,
            self::TK,
            self::TO,
            self::TT,
            self::TN,
            self::TR,
            self::TM,
            self::TC,
            self::TV,
            self::UM,
            self::VI,
            self::UG,
            self::UA,
            self::AE,
            self::GB,
            self::US,
            self::UY,
            self::UZ,
            self::VU,
            self::VA,
            self::VE,
            self::VN,
            self::WF,
            self::EH,
            self::YE,
            self::ZM,
            self::ZW
        ];
    }
}


