<?php
/**
 * LocaleCode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AirEml
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * airEml - API
 *
 * airEml - API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AirEml\Model;
use \AirEml\ObjectSerializer;

/**
 * LocaleCode Class Doc Comment
 *
 * @category Class
 * @description The language code of the locale. The language code is a two-letter code defined in ISO 639-1. The language code is followed by an underscore and a two-letter country code defined in ISO 3166-1 alpha-2. For example, en_US represents the English language used in the United States.
 * @package  AirEml
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LocaleCode
{
    /**
     * Possible values of this enum
     */
    public const EN = 'en';

    public const AR = 'ar';

    public const AZ = 'az';

    public const BS = 'bs';

    public const CA = 'ca';

    public const HR = 'hr';

    public const CS = 'cs';

    public const DA = 'da';

    public const NL = 'nl';

    public const ET = 'et';

    public const FI = 'fi';

    public const FR = 'fr';

    public const KA = 'ka';

    public const BG = 'bg';

    public const DE = 'de';

    public const EL = 'el';

    public const HI = 'hi';

    public const HE = 'he';

    public const HU = 'hu';

    public const ID = 'id';

    public const IT = 'it';

    public const JA = 'ja';

    public const KO = 'ko';

    public const LV = 'lv';

    public const LT = 'lt';

    public const MS = 'ms';

    public const NB = 'nb';

    public const FA = 'fa';

    public const PL = 'pl';

    public const PT = 'pt';

    public const PA = 'pa';

    public const RO = 'ro';

    public const RU = 'ru';

    public const SR = 'sr';

    public const SK = 'sk';

    public const ES = 'es';

    public const SV = 'sv';

    public const TH = 'th';

    public const TR = 'tr';

    public const UK = 'uk';

    public const VI = 'vi';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EN,
            self::AR,
            self::AZ,
            self::BS,
            self::CA,
            self::HR,
            self::CS,
            self::DA,
            self::NL,
            self::ET,
            self::FI,
            self::FR,
            self::KA,
            self::BG,
            self::DE,
            self::EL,
            self::HI,
            self::HE,
            self::HU,
            self::ID,
            self::IT,
            self::JA,
            self::KO,
            self::LV,
            self::LT,
            self::MS,
            self::NB,
            self::FA,
            self::PL,
            self::PT,
            self::PA,
            self::RO,
            self::RU,
            self::SR,
            self::SK,
            self::ES,
            self::SV,
            self::TH,
            self::TR,
            self::UK,
            self::VI
        ];
    }
}


