<?php
/**
 * EmailTemplatesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * airEml - API (full)
 *
 * airEml - API (full)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmailTemplatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailTemplatesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createEmailTemplate
     *
     * Create a New Email Notification Template.
     *
     */
    public function testCreateEmailTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEmailTemplateContent
     *
     * Create a Content in the Email Notification Template.
     *
     */
    public function testCreateEmailTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEmailTemplate
     *
     * Delete a Email Notification Template.
     *
     */
    public function testDeleteEmailTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEmailTemplateContent
     *
     * Delete a Content from the Email Notification Template.
     *
     */
    public function testDeleteEmailTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEmailTemplate
     *
     * Retrieve an Existing Email Notification Template.
     *
     */
    public function testGetEmailTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEmailTemplateContent
     *
     * Retrieve an Existing Content from the Email Notification Template.
     *
     */
    public function testGetEmailTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEmailTemplateContents
     *
     * List All Contents from the Email Notification Template.
     *
     */
    public function testListEmailTemplateContents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEmailTemplates
     *
     * List All Email Notification Templates.
     *
     */
    public function testListEmailTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEmailTemplate
     *
     * Update a Email Notification Template.
     *
     */
    public function testUpdateEmailTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEmailTemplateContent
     *
     * Update a Content in the Email Notification Template.
     *
     */
    public function testUpdateEmailTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
