<?php
/**
 * EmailSettingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * airEml - API (full)
 *
 * airEml - API (full)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmailSettingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailSettingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createEmailChannel
     *
     * Create a New Email Notification Channel.
     *
     */
    public function testCreateEmailChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEmailChannelRoutingRule
     *
     * Create a Routing-rule in the Email Notification Channel.
     *
     */
    public function testCreateEmailChannelRoutingRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEmailSender
     *
     * Create a New Email Notification Sender.
     *
     */
    public function testCreateEmailSender()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEmailTransport
     *
     * Create a New Email Notification Transport.
     *
     */
    public function testCreateEmailTransport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEmailChannel
     *
     * Delete a Email Notification Channel.
     *
     */
    public function testDeleteEmailChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEmailChannelRoutingRule
     *
     * Delete a Routing-rule from the Email Notification Channel.
     *
     */
    public function testDeleteEmailChannelRoutingRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEmailSender
     *
     * Delete a Email Notification Sender.
     *
     */
    public function testDeleteEmailSender()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEmailTransport
     *
     * Delete a Email Notification Transport.
     *
     */
    public function testDeleteEmailTransport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEmailChannel
     *
     * Retrieve an Existing Email Notification Channel.
     *
     */
    public function testGetEmailChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEmailChannelRoutingRule
     *
     * Retrieve an Existing Routing-rule from the Email Notification Channel.
     *
     */
    public function testGetEmailChannelRoutingRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEmailSender
     *
     * Retrieve an Existing Email Notification Sender.
     *
     */
    public function testGetEmailSender()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEmailTransport
     *
     * Retrieve an Existing Email Notification Transport.
     *
     */
    public function testGetEmailTransport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEmailChannelRoutingRules
     *
     * List All Routing-rules from the Email Notification Channel.
     *
     */
    public function testListEmailChannelRoutingRules()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEmailChannels
     *
     * List All Email Notification Channels.
     *
     */
    public function testListEmailChannels()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEmailSenders
     *
     * List All Email Notification Senders.
     *
     */
    public function testListEmailSenders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEmailTransports
     *
     * List All Email Notification Transports.
     *
     */
    public function testListEmailTransports()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEmailChannel
     *
     * Update a Email Notification Channel.
     *
     */
    public function testUpdateEmailChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEmailChannelRoutingRule
     *
     * Update a Routing-rule in the Email Notification Channel.
     *
     */
    public function testUpdateEmailChannelRoutingRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEmailSender
     *
     * Update a Email Notification Sender.
     *
     */
    public function testUpdateEmailSender()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEmailTransport
     *
     * Update a Email Notification Transport.
     *
     */
    public function testUpdateEmailTransport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
