<?php
/**
 * NotificationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * airEml - API (full)
 *
 * airEml - API (full)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NotificationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NotificationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getEmailNotification
     *
     * Retrieve an Existing Email Notification.
     *
     */
    public function testGetEmailNotification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEmailNotificationStates
     *
     * Retrieve an Existing Email Notification States.
     *
     */
    public function testGetEmailNotificationStates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPushNotification
     *
     * Retrieve an Existing Push Notification.
     *
     */
    public function testGetPushNotification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPushNotificationStates
     *
     * Retrieve an Existing Push Notification States.
     *
     */
    public function testGetPushNotificationStates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSmsNotification
     *
     * Retrieve an Existing SMS Notification.
     *
     */
    public function testGetSmsNotification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSmsNotificationStates
     *
     * Retrieve an Existing Sms Notification States.
     *
     */
    public function testGetSmsNotificationStates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEmailNotifications
     *
     * List All Email Notifications.
     *
     */
    public function testListEmailNotifications()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPushNotifications
     *
     * List All Push Notifications.
     *
     */
    public function testListPushNotifications()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSmsNotifications
     *
     * List All SMS Notifications.
     *
     */
    public function testListSmsNotifications()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
