<?php
/**
 * PushTemplatesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * airEml - API (full)
 *
 * airEml - API (full)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PushTemplatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PushTemplatesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createPushTemplate
     *
     * Create a New Push Notification Template.
     *
     */
    public function testCreatePushTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPushTemplateContent
     *
     * Create a Content in the Push Notification Template.
     *
     */
    public function testCreatePushTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePushTemplate
     *
     * Delete a Push Notification Template.
     *
     */
    public function testDeletePushTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePushTemplateContent
     *
     * Delete a Content from the Push Notification Template.
     *
     */
    public function testDeletePushTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPushTemplate
     *
     * Retrieve an Existing Push Notification Template.
     *
     */
    public function testGetPushTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPushTemplateContent
     *
     * Retrieve an Existing Content from the Push Notification Template.
     *
     */
    public function testGetPushTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPushTemplateContents
     *
     * List All Contents from the Push Notification Template.
     *
     */
    public function testListPushTemplateContents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPushTemplates
     *
     * List All Push Notification Templates.
     *
     */
    public function testListPushTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePushTemplate
     *
     * Update a Push Notification Template.
     *
     */
    public function testUpdatePushTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePushTemplateContent
     *
     * Update a Content in the Push Notification Template.
     *
     */
    public function testUpdatePushTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
