<?php
/**
 * SMSSettingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * airEml - API (full)
 *
 * airEml - API (full)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SMSSettingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SMSSettingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createSmsChannel
     *
     * Create a New SMS Channel.
     *
     */
    public function testCreateSmsChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSmsTransport
     *
     * Create a New SMS Transport.
     *
     */
    public function testCreateSmsTransport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSmsChannel
     *
     * Delete a SMS Channel.
     *
     */
    public function testDeleteSmsChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSmsRoutingRule
     *
     * Delete a SMS Channel Rule.
     *
     */
    public function testDeleteSmsRoutingRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSmsTransport
     *
     * Delete a SMS Transport.
     *
     */
    public function testDeleteSmsTransport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSmsChannel
     *
     * Retrieve an Existing SMS Channel.
     *
     */
    public function testGetSmsChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSmsRoutingRule
     *
     * Retrieve an Existing SMS Channel Rule.
     *
     */
    public function testGetSmsRoutingRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSmsSender
     *
     * Retrieve an Existing Number from the SMS Transport.
     *
     */
    public function testGetSmsSender()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSmsTransport
     *
     * Retrieve an Existing SMS Transport.
     *
     */
    public function testGetSmsTransport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebhookByTransport
     *
     * Webhook url generated by transport.
     *
     */
    public function testGetWebhookByTransport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAllSmsSenders
     *
     * List All SMS Transport Numbers.
     *
     */
    public function testListAllSmsSenders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSmsChannels
     *
     * List All SMS Channels.
     *
     */
    public function testListSmsChannels()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSmsChannelsRules
     *
     * List of all Rules from the SMS Channel.
     *
     */
    public function testListSmsChannelsRules()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSmsSenders
     *
     * List All Numbers from the SMS Transport.
     *
     */
    public function testListSmsSenders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSmsTransports
     *
     * List All SMS Transports.
     *
     */
    public function testListSmsTransports()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for saveSmsRoutingRule
     *
     * Save a parameters SMS Channel Rule.
     *
     */
    public function testSaveSmsRoutingRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSmsChannel
     *
     * Update a SMS Channel.
     *
     */
    public function testUpdateSmsChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSmsRoutingRule
     *
     * Update a SMS Channel Rule.
     *
     */
    public function testUpdateSmsRoutingRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSmsTransport
     *
     * Update a SMS Transport.
     *
     */
    public function testUpdateSmsTransport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
