<?php
/**
 * SMSTemplatesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * airEml - API (full)
 *
 * airEml - API (full)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SMSTemplatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SMSTemplatesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createSmsTemplate
     *
     * Create a New SMS Template.
     *
     */
    public function testCreateSmsTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSmsTemplate
     *
     * Delete a SMS Template.
     *
     */
    public function testDeleteSmsTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSmsTemplateContent
     *
     * Delete a Content from the SMS Template.
     *
     */
    public function testDeleteSmsTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSmsTemplate
     *
     * Retrieve an Existing SMS Template.
     *
     */
    public function testGetSmsTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSmsTemplateContent
     *
     * Retrieve an Existing Content from the SMS Template.
     *
     */
    public function testGetSmsTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSmsTemplateContents
     *
     * List All Contents from the SMS Template.
     *
     */
    public function testListSmsTemplateContents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSmsTemplates
     *
     * List All SMS Templates.
     *
     */
    public function testListSmsTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for saveSmsTemplateContent
     *
     * Save a Content in the SMS Template.
     *
     */
    public function testSaveSmsTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSmsTemplate
     *
     * Update a SMS Template.
     *
     */
    public function testUpdateSmsTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSmsTemplateContent
     *
     * Update a Content in the SMS Notification Template.
     *
     */
    public function testUpdateSmsTemplateContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
